(function () {
  const categories = [
    {
      id: "coffee",
      group: "Beverage",
      name: "Coffee",
      label: "커피",
      description: "에스프레소와 원두의 향을 중심으로 한 음료",
    },
    {
      id: "ade",
      group: "Beverage",
      name: "Ade",
      label: "에이드",
      description: "과일과 탄산의 청량함을 살린 음료",
    },
    {
      id: "tea",
      group: "Beverage",
      name: "Tea",
      label: "티",
      description: "가볍게 즐기기 좋은 허브와 찻잎 음료",
    },
    {
      id: "bread",
      group: "Food",
      name: "Bread",
      label: "브레드",
      description: "커피와 함께 즐기기 좋은 베이커리",
    },
    {
      id: "cake",
      group: "Food",
      name: "Cake",
      label: "케이크",
      description: "달콤한 휴식을 위한 디저트 케이크",
    },
  ];

  const menus = [
    {
      id: "americano",
      categoryId: "coffee",
      name: "아메리카노",
      englishName: "Americano",
      price: 4500,
      image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=900&q=80",
      description: "고소한 원두 향과 깔끔한 끝맛이 살아 있는 기본 커피입니다.",
      tags: ["best", "hot", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "cafe-latte",
      categoryId: "coffee",
      name: "카페 라떼",
      englishName: "Cafe Latte",
      price: 5200,
      image: "https://images.unsplash.com/photo-1570968915860-54d5c301fa9f?auto=format&fit=crop&w=900&q=80",
      description: "에스프레소에 부드러운 우유를 더한 균형 좋은 라떼입니다.",
      tags: ["signature", "hot", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "vanilla-latte",
      categoryId: "coffee",
      name: "바닐라 라떼",
      englishName: "Vanilla Latte",
      price: 5800,
      image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80",
      description: "은은한 바닐라 향과 라떼의 고소함이 어우러진 달콤한 커피입니다.",
      tags: ["sweet", "hot", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "caramel-macchiato",
      categoryId: "coffee",
      name: "카라멜 마키아토",
      englishName: "Caramel Macchiato",
      price: 6100,
      image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=900&q=80",
      description: "카라멜의 진한 단맛과 에스프레소의 쌉싸름함이 조화로운 메뉴입니다.",
      tags: ["sweet", "signature", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "cold-brew",
      categoryId: "coffee",
      name: "콜드브루",
      englishName: "Cold Brew",
      price: 5500,
      image: "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=900&q=80",
      description: "천천히 추출해 산미는 낮추고 깊은 풍미를 살린 아이스 커피입니다.",
      tags: ["iced", "deep"],
      options: {
        temperature: ["iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "einspanner",
      categoryId: "coffee",
      name: "아인슈페너",
      englishName: "Einspanner",
      price: 6300,
      image: "https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&w=900&q=80",
      description: "진한 커피 위에 부드러운 크림을 올린 시그니처 커피입니다.",
      tags: ["cream", "signature", "iced"],
      options: {
        temperature: ["iced"],
        sizes: ["regular"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "cafe-mocha",
      categoryId: "coffee",
      name: "카페 모카",
      englishName: "Cafe Mocha",
      price: 6000,
      image: "https://images.unsplash.com/photo-1512568400610-62da28bc8a13?auto=format&fit=crop&w=900&q=80",
      description: "에스프레소와 초콜릿, 우유가 부드럽게 어우러진 달콤한 커피입니다.",
      tags: ["sweet", "hot", "iced"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "flat-white",
      categoryId: "coffee",
      name: "플랫 화이트",
      englishName: "Flat White",
      price: 5700,
      image: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=900&q=80",
      description: "진한 에스프레소와 고운 밀크폼으로 커피의 농도를 살린 메뉴입니다.",
      tags: ["hot", "deep"],
      options: {
        temperature: ["hot"],
        sizes: ["regular"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "lemon-ade",
      categoryId: "ade",
      name: "레몬 에이드",
      englishName: "Lemon Ade",
      price: 5700,
      image: "https://images.unsplash.com/photo-1621263764928-df1444c5e859?auto=format&fit=crop&w=900&q=80",
      description: "상큼한 레몬과 탄산이 시원하게 퍼지는 기본 에이드입니다.",
      tags: ["iced", "fresh"],
      options: {
        temperature: ["iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "grapefruit-ade",
      categoryId: "ade",
      name: "자몽 에이드",
      englishName: "Grapefruit Ade",
      price: 5900,
      image: "https://images.unsplash.com/photo-1523371054106-bbf80586c38c?auto=format&fit=crop&w=900&q=80",
      description: "자몽의 쌉싸름한 향과 과육감이 매력적인 에이드입니다.",
      tags: ["iced", "bitter-sweet"],
      options: {
        temperature: ["iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "green-grape-ade",
      categoryId: "ade",
      name: "청포도 에이드",
      englishName: "Green Grape Ade",
      price: 6100,
      image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=80",
      description: "청포도의 산뜻한 단맛을 탄산으로 가볍게 살린 음료입니다.",
      tags: ["iced", "sweet"],
      options: {
        temperature: ["iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "peach-ade",
      categoryId: "ade",
      name: "복숭아 에이드",
      englishName: "Peach Ade",
      price: 5900,
      image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=900&q=80",
      description: "복숭아의 부드러운 달콤함과 탄산의 청량함이 어울립니다.",
      tags: ["iced", "sweet"],
      options: {
        temperature: ["iced"],
        sizes: ["regular", "large"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "earl-grey",
      categoryId: "tea",
      name: "얼그레이",
      englishName: "Earl Grey",
      price: 4800,
      image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=900&q=80",
      description: "베르가못 향이 은은하게 퍼지는 클래식 홍차입니다.",
      tags: ["hot", "light"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "chamomile",
      categoryId: "tea",
      name: "캐모마일",
      englishName: "Chamomile",
      price: 4700,
      image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=900&q=80",
      description: "편안한 꽃향으로 부담 없이 마시기 좋은 허브티입니다.",
      tags: ["hot", "caffeine-free"],
      options: {
        temperature: ["hot"],
        sizes: ["regular"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "hibiscus-tea",
      categoryId: "tea",
      name: "히비스커스 티",
      englishName: "Hibiscus Tea",
      price: 5000,
      image: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=900&q=80",
      description: "새콤한 풍미와 붉은 색감이 돋보이는 산뜻한 허브티입니다.",
      tags: ["hot", "iced", "fresh"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "jeju-green-tea",
      categoryId: "tea",
      name: "제주 녹차",
      englishName: "Jeju Green Tea",
      price: 5100,
      image: "https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=900&q=80",
      description: "깔끔한 풀 향과 은은한 감칠맛이 느껴지는 녹차입니다.",
      tags: ["hot", "clean"],
      options: {
        temperature: ["hot", "iced"],
        sizes: ["regular"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "croissant",
      categoryId: "bread",
      name: "크루아상",
      englishName: "Croissant",
      price: 4200,
      image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=900&q=80",
      description: "겹겹이 쌓인 버터 풍미와 바삭한 식감이 좋은 기본 베이커리입니다.",
      tags: ["bakery", "morning"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "garlic-baguette",
      categoryId: "bread",
      name: "갈릭 바게트",
      englishName: "Garlic Baguette",
      price: 4800,
      image: "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?auto=format&fit=crop&w=900&q=80",
      description: "바삭한 바게트에 갈릭 버터의 짭짤한 풍미를 더했습니다.",
      tags: ["bakery", "savory"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "salt-bread",
      categoryId: "bread",
      name: "소금빵",
      englishName: "Salt Bread",
      price: 3900,
      image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80",
      description: "버터의 고소함과 소금의 짭짤함이 깔끔하게 어울리는 빵입니다.",
      tags: ["bakery", "best"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "cinnamon-roll",
      categoryId: "bread",
      name: "시나몬 롤",
      englishName: "Cinnamon Roll",
      price: 4600,
      image: "https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=900&q=80",
      description: "향긋한 시나몬과 달콤한 글레이즈가 어우러진 디저트 빵입니다.",
      tags: ["bakery", "sweet"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "basque-cheesecake",
      categoryId: "cake",
      name: "바스크 치즈케이크",
      englishName: "Basque Cheesecake",
      price: 6800,
      image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=900&q=80",
      description: "진한 치즈 풍미와 그을린 표면의 고소함이 매력적인 케이크입니다.",
      tags: ["cake", "best"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "tiramisu",
      categoryId: "cake",
      name: "티라미수",
      englishName: "Tiramisu",
      price: 6500,
      image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=900&q=80",
      description: "커피 향과 마스카포네 크림이 부드럽게 어우러지는 디저트입니다.",
      tags: ["cake", "coffee"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
    {
      id: "chocolate-cake",
      categoryId: "cake",
      name: "초콜릿 케이크",
      englishName: "Chocolate Cake",
      price: 6600,
      image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=80",
      description: "진한 초콜릿 크림과 촉촉한 시트가 어우러진 케이크입니다.",
      tags: ["cake", "sweet"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: true,
    },
    {
      id: "earl-grey-cake",
      categoryId: "cake",
      name: "얼그레이 케이크",
      englishName: "Earl Grey Cake",
      price: 6700,
      image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=900&q=80",
      description: "얼그레이 향을 머금은 크림과 폭신한 시트가 은은한 케이크입니다.",
      tags: ["cake", "tea"],
      options: {
        temperature: ["room"],
        sizes: ["single"],
      },
      isSoldOut: false,
      isRecommended: false,
    },
  ];

  const orders = [];

  window.CafeData = Object.freeze({
    categories,
    menus,
    orders,
  });
})();
